version: "3"
services:
  swagger-ui:
    image: swaggerapi/swagger-ui
    container_name: "swagger-ui"
    ports:
      - "8002:8080"
    volumes:
      - ./gen/http/openapi.yaml:/openapi.yaml
    environment:
      SWAGGER_JSON: /openapi.yaml
