swagger: "2.0"
info:
    title: Epup Index Creator
    version: 0.0.1
host: localhost:8000
consumes:
    - application/json
    - application/xml
    - application/gob
produces:
    - application/json
    - application/xml
    - application/gob
paths:
    /books/{isbn}:
        get:
            tags:
                - epub_index_creator
            summary: List epub_index_creator
            operationId: epub_index_creator#List
            parameters:
                - name: isbn
                  in: path
                  description: ISBN of the book
                  required: true
                  type: string
            responses:
                "200":
                    description: OK response.
                    schema:
                        $ref: '#/definitions/EpubIndexCreatorListResponseBody'
            schemes:
                - http
    /openapi.json:
        get:
            tags:
                - epub_index_creator
            summary: Download ./gen/http/openapi.json
            operationId: epub_index_creator#/openapi.json
            responses:
                "200":
                    description: File downloaded
                    schema:
                        type: file
            schemes:
                - http
definitions:
    EpubIndexCreatorListResponseBody:
        title: EpubIndexCreatorListResponseBody
        type: object
        properties:
            author:
                type: string
                description: Author of the book
                example: Ut veniam est aut occaecati odio corrupti.
            isbn:
                type: string
                description: ISBN of the book
                example: Velit quo reiciendis est est ut.
            pages:
                type: array
                items:
                    $ref: '#/definitions/PageResponseBody'
                description: Pages of the book
                example:
                    - keywords:
                        - keyword: Ipsa porro rerum qui in omnis.
                        - keyword: Ipsa porro rerum qui in omnis.
                      title: Nam quibusdam vero rem aliquam voluptatibus.
                    - keywords:
                        - keyword: Ipsa porro rerum qui in omnis.
                        - keyword: Ipsa porro rerum qui in omnis.
                      title: Nam quibusdam vero rem aliquam voluptatibus.
            title:
                type: string
                description: Title of the book
                example: Aspernatur velit dolores aperiam adipisci qui.
        example:
            author: Officiis totam.
            isbn: Aliquam ab dolor.
            pages:
                - keywords:
                    - keyword: Ipsa porro rerum qui in omnis.
                    - keyword: Ipsa porro rerum qui in omnis.
                  title: Nam quibusdam vero rem aliquam voluptatibus.
                - keywords:
                    - keyword: Ipsa porro rerum qui in omnis.
                    - keyword: Ipsa porro rerum qui in omnis.
                  title: Nam quibusdam vero rem aliquam voluptatibus.
                - keywords:
                    - keyword: Ipsa porro rerum qui in omnis.
                    - keyword: Ipsa porro rerum qui in omnis.
                  title: Nam quibusdam vero rem aliquam voluptatibus.
                - keywords:
                    - keyword: Ipsa porro rerum qui in omnis.
                    - keyword: Ipsa porro rerum qui in omnis.
                  title: Nam quibusdam vero rem aliquam voluptatibus.
            title: Nulla corporis aspernatur ut dicta.
    KeywordResponseBody:
        title: KeywordResponseBody
        type: object
        properties:
            keyword:
                type: string
                description: Keyword of the page
                example: Unde recusandae saepe velit ullam omnis.
        example:
            keyword: Atque labore ad.
    PageResponseBody:
        title: PageResponseBody
        type: object
        properties:
            keywords:
                type: array
                items:
                    $ref: '#/definitions/KeywordResponseBody'
                description: Keywords of the page
                example:
                    - keyword: Ipsa porro rerum qui in omnis.
                    - keyword: Ipsa porro rerum qui in omnis.
            title:
                type: string
                description: Title of the page
                example: Commodi sint sint repellat sapiente porro nesciunt.
        example:
            keywords:
                - keyword: Ipsa porro rerum qui in omnis.
                - keyword: Ipsa porro rerum qui in omnis.
                - keyword: Ipsa porro rerum qui in omnis.
            title: Quae consequatur.
