// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/marutaku/epub-index-creator/indexer/ent/keyword"
	"github.com/marutaku/epub-index-creator/indexer/ent/predicate"
)

// KeywordUpdate is the builder for updating Keyword entities.
type KeywordUpdate struct {
	config
	hooks    []Hook
	mutation *KeywordMutation
}

// Where appends a list predicates to the KeywordUpdate builder.
func (ku *KeywordUpdate) Where(ps ...predicate.Keyword) *KeywordUpdate {
	ku.mutation.Where(ps...)
	return ku
}

// SetKeyword sets the "keyword" field.
func (ku *KeywordUpdate) SetKeyword(s string) *KeywordUpdate {
	ku.mutation.SetKeyword(s)
	return ku
}

// SetNillableKeyword sets the "keyword" field if the given value is not nil.
func (ku *KeywordUpdate) SetNillableKeyword(s *string) *KeywordUpdate {
	if s != nil {
		ku.SetKeyword(*s)
	}
	return ku
}

// Mutation returns the KeywordMutation object of the builder.
func (ku *KeywordUpdate) Mutation() *KeywordMutation {
	return ku.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (ku *KeywordUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, ku.sqlSave, ku.mutation, ku.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (ku *KeywordUpdate) SaveX(ctx context.Context) int {
	affected, err := ku.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (ku *KeywordUpdate) Exec(ctx context.Context) error {
	_, err := ku.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (ku *KeywordUpdate) ExecX(ctx context.Context) {
	if err := ku.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (ku *KeywordUpdate) check() error {
	if v, ok := ku.mutation.Keyword(); ok {
		if err := keyword.KeywordValidator(v); err != nil {
			return &ValidationError{Name: "keyword", err: fmt.Errorf(`ent: validator failed for field "Keyword.keyword": %w`, err)}
		}
	}
	return nil
}

func (ku *KeywordUpdate) sqlSave(ctx context.Context) (n int, err error) {
	if err := ku.check(); err != nil {
		return n, err
	}
	_spec := sqlgraph.NewUpdateSpec(keyword.Table, keyword.Columns, sqlgraph.NewFieldSpec(keyword.FieldID, field.TypeInt))
	if ps := ku.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := ku.mutation.Keyword(); ok {
		_spec.SetField(keyword.FieldKeyword, field.TypeString, value)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, ku.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{keyword.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	ku.mutation.done = true
	return n, nil
}

// KeywordUpdateOne is the builder for updating a single Keyword entity.
type KeywordUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *KeywordMutation
}

// SetKeyword sets the "keyword" field.
func (kuo *KeywordUpdateOne) SetKeyword(s string) *KeywordUpdateOne {
	kuo.mutation.SetKeyword(s)
	return kuo
}

// SetNillableKeyword sets the "keyword" field if the given value is not nil.
func (kuo *KeywordUpdateOne) SetNillableKeyword(s *string) *KeywordUpdateOne {
	if s != nil {
		kuo.SetKeyword(*s)
	}
	return kuo
}

// Mutation returns the KeywordMutation object of the builder.
func (kuo *KeywordUpdateOne) Mutation() *KeywordMutation {
	return kuo.mutation
}

// Where appends a list predicates to the KeywordUpdate builder.
func (kuo *KeywordUpdateOne) Where(ps ...predicate.Keyword) *KeywordUpdateOne {
	kuo.mutation.Where(ps...)
	return kuo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (kuo *KeywordUpdateOne) Select(field string, fields ...string) *KeywordUpdateOne {
	kuo.fields = append([]string{field}, fields...)
	return kuo
}

// Save executes the query and returns the updated Keyword entity.
func (kuo *KeywordUpdateOne) Save(ctx context.Context) (*Keyword, error) {
	return withHooks(ctx, kuo.sqlSave, kuo.mutation, kuo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (kuo *KeywordUpdateOne) SaveX(ctx context.Context) *Keyword {
	node, err := kuo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (kuo *KeywordUpdateOne) Exec(ctx context.Context) error {
	_, err := kuo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (kuo *KeywordUpdateOne) ExecX(ctx context.Context) {
	if err := kuo.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (kuo *KeywordUpdateOne) check() error {
	if v, ok := kuo.mutation.Keyword(); ok {
		if err := keyword.KeywordValidator(v); err != nil {
			return &ValidationError{Name: "keyword", err: fmt.Errorf(`ent: validator failed for field "Keyword.keyword": %w`, err)}
		}
	}
	return nil
}

func (kuo *KeywordUpdateOne) sqlSave(ctx context.Context) (_node *Keyword, err error) {
	if err := kuo.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(keyword.Table, keyword.Columns, sqlgraph.NewFieldSpec(keyword.FieldID, field.TypeInt))
	id, ok := kuo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Keyword.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := kuo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, keyword.FieldID)
		for _, f := range fields {
			if !keyword.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != keyword.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := kuo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := kuo.mutation.Keyword(); ok {
		_spec.SetField(keyword.FieldKeyword, field.TypeString, value)
	}
	_node = &Keyword{config: kuo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, kuo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{keyword.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	kuo.mutation.done = true
	return _node, nil
}
