// Code generated by ent, DO NOT EDIT.

package page

import (
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the page type in the database.
	Label = "page"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldTitle holds the string denoting the title field in the database.
	FieldTitle = "title"
	// EdgeKeywords holds the string denoting the keywords edge name in mutations.
	EdgeKeywords = "keywords"
	// Table holds the table name of the page in the database.
	Table = "pages"
	// KeywordsTable is the table that holds the keywords relation/edge.
	KeywordsTable = "keywords"
	// KeywordsInverseTable is the table name for the Keyword entity.
	// It exists in this package in order to avoid circular dependency with the "keyword" package.
	KeywordsInverseTable = "keywords"
	// KeywordsColumn is the table column denoting the keywords relation/edge.
	KeywordsColumn = "page_keywords"
)

// Columns holds all SQL columns for page fields.
var Columns = []string{
	FieldID,
	FieldTitle,
}

// ForeignKeys holds the SQL foreign-keys that are owned by the "pages"
// table and are not defined as standalone fields in the schema.
var ForeignKeys = []string{
	"book_pages",
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	for i := range ForeignKeys {
		if column == ForeignKeys[i] {
			return true
		}
	}
	return false
}

var (
	// TitleValidator is a validator for the "title" field. It is called by the builders before save.
	TitleValidator func(string) error
)

// OrderOption defines the ordering options for the Page queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByTitle orders the results by the title field.
func ByTitle(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTitle, opts...).ToFunc()
}

// ByKeywordsCount orders the results by keywords count.
func ByKeywordsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newKeywordsStep(), opts...)
	}
}

// ByKeywords orders the results by keywords terms.
func ByKeywords(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newKeywordsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}
func newKeywordsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(KeywordsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, KeywordsTable, KeywordsColumn),
	)
}
